### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dwvisser** [stevedekorte/vertexdb#20]
There should be an explicit LICENSE or LICENSE.txt file.

**Comment by stevedekorte** [comment]
https://github.com/stevedekorte/vertexdb/tree/master/license

**Comment by dwvisser** [comment]
Thanks for pointing that out. I'm accustomed to looking for `^LICENSE(\.[a-d]{2,3})?$`

**Comment by stevedekorte** [comment]
Yes, sorry if it's confusing. I'll move it when I get a chance. Would also accept a patch for this.

**Comment by dwvisser** [comment]
was closed by https://github.com/stevedekorte/vertexdb/commit/ae449a014bf06f5cd02a0fa73183ebfbe9076adb
